# -*- coding: utf-8 -*-
"""Python ADV Questions array

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HoSeusqkT8fH-Y1P-yzTt6zMWMbPGgmi

**All the 33 questions for python**

Reverse an array
"""

l = [1,4,3,2,6,8,5,9]
NL = []
for i in reversed(l):
  NL.append(i)
print(NL)

"""Find max and min element"""

l = [11,48,33,274,623,84,524,22,121,54,47,87,33,64,52,25,9]
max_elem = l[0]
for i in l:
  if i > max_elem:
    max_elem = i
print(max_elem)
min_elem = l[0]
for i in l:
  if i < min_elem:
    min_elem = i
print(min_elem)

"""find the sum of elements"""

l = [11,48,33,274,623,84,524,22,121,54,47,87,33,64,52,25,9]
list_sum = 0
for i in l:
  list_sum += i
print(list_sum)

"""Find second largest element"""

l = [11,48,33,274,623,84,524,22,121,54,47,87,33,64,52,25,9]
l.sort()
second_largest = l[-2]
print(second_largest)

"""Count frequency of elements"""

l = [11,48,33,274,623,84,524,22,121,54,47,87,33,64,52,25,9]
frequency = {}
for i in l:
  if i not in frequency:
    frequency[i] = 1
  else:
    frequency[i] += 1
print(frequency)

"""check if array is sorted"""

l = [1,2,3,4,5,6,7,8,8,9,10]
sorted_flag = True
for i in range (len(l)-1):
  if l[i] > l[i+1]:
    sorted_flag = False
print(sorted_flag)

"""Rotate Array by k Positions: Rotate the array to the right by k positions."""

l = [11,48,33,274,623,84,524,22,121,54,47,87,33,64,52,25,9]
k_rotations = int(input("state how many rotations you want the list to rotate."))
a = l[-k_rotations:]
b = l[:-k_rotations]
print(a+b)

"""Find Pair with Given Sum: Find a pair of elements that adds up to a target sum.

here I am coming up with some problems that I didn't realise at first, the problems are :-
* the self pairing problem , ex 10-5 =5 but I only have one 5 in the list.
* the double printing problem , basically it takes 4,6 and 6,4
"""

target_sum = int(input("what is the target sum only till 29"))
l = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
dict_l = dict(enumerate(l))
for i in l:
  dif_target = target_sum - i
  if  dif_target in dict_l and dif_target != i:
    print(f"the pair of elements that add up to {target_sum} are {dif_target} and {i}")

"""This is the repeat of the previous question with a different way to fix the previous problems"""

target_sum = int(input("what is the target sum "))
l = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
seen_elems = {}
for i in l:
  dif_target = target_sum - i
  if dif_target in l:
    if dif_target not in seen_elems:
      print(f"the pair of elements that add up to {target_sum} are {dif_target} and {i}")
      seen_elems[i] = True

"""Remove Duplicates from Array: Remove duplicates from the array while maintaining order."""

g = [11,48,33,274,623,84,524,22,121,54,47,87,33,64,52,25,9,9,11,22,33]
unique_elems = []
for i in g:
  if i not in unique_elems:
    unique_elems.append(i)
print (unique_elems)

""" Merge Two Sorted Arrays"""

array_1 = [1, 3, 5, 7, 9, 11]
array_2 = [2, 4, 6, 8, 10, 12, 14, 16]
i = 0
j = 0
merged_array = []
while i < len(array_1) and j < len(array_2):
  if array_1[i] < array_2[j]:
    merged_array.append(array_1[i])
    i = i + 1
  elif array_2[j] < array_1[i]:
    merged_array.append(array_2[j])
    j = j+1
merged_array += array_1[i:]
merged_array += array_2[j:]
print(merged_array)

"""Remove given Element from Array"""

elem_remove = int(input("what element do you want to remove form the array"))
array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
new_array = []
for i in array:
  if i != elem_remove:
    new_array.append(i)

print(new_array)

"""Find the Missing Number: Find the missing number in an array of size n containing numbers from 1 to n."""

array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,20]
j = 1
for i in array:
  if i != j:
    print(f"the missing number in the array is {j}")
    j = i
  j += 1

"""Find Duplicates in an Array"""

l = [11,48,33,274,623,84,524,22,121,54,47,87,33,64,52,25,9,54,11,22,33]
unique_elems = {}
duplicate = []
for i in l:
  if i in unique_elems:
    duplicate.append(i)
  else:
    unique_elems[i] = True
print(f"these are the duplicates in the array {duplicate}")

"""Find Intersection of Two Arrays: Find the common elements between two arrays."""

array1 = [10, 20, 20, 30, 40, 50, 50]
array2= [50, 50, 60, 20, 70, 80]
common_elems = []
for i in array1:
  for j in array2:
    if i == j and i not in common_elems:
      common_elems.append(i)
print(common_elems)

"""Find Union of Two Arrays"""

array1 = [10, 20, 20, 30, 40, 50, 50]
array2= [50, 50, 60, 20, 70, 80]
union = []
for i in array1:
  if i not in union:
    union.append(i)
for j in array2:
  if j not in union:
    union.append(j)
print(union)

"""Check if Two Arrays Are Equal: if two arrays contain the same elements"""

array1 = [1, 1, 2]
array2 = [1, 1, 2]
if len(array1) != len(array2):
  print("the arrays are not equal")
else:
  if sorted(array1) == sorted(array2):
    print("the arrays are equal")
  else:
    print("the arrays are not equal")

"""Find the Leader Elements: An element is a leader if it is greater than all elements to its right."""

array = [16, 17, 4, 3, 5, 2]
rev_array = list(reversed(array))
leader_elements = []
current_max = -1
for i in range(len(rev_array)):
  if rev_array[i] > current_max:
    leader_elements.append(rev_array[i])
    current_max = rev_array[i]
leader_elements.reverse()
print(leader_elements)

"""Move Zeroes to End: Move all zeroes in an array to the end while maintaining the order of non-zero elements."""

l = [0, 1, 0, 3, 12, 0, 0, 9, 5]
new_l = []
zero_counter = 0
for i in l:
  if i != 0:
    new_l.append(i)
  else:
    zero_counter += 1
while zero_counter > 0:
  new_l.append(0)
  zero_counter -= 1
print(new_l)

"""Find Subarray with Given Sum."""

array = [1,2,3,7,5]
Target_sum = 12
sum_subarr = []
l,curr_value, = -1,0
for i in range(len(array)):
  curr_value += array[i]
  while curr_value > Target_sum:
    l +=1
    curr_value -= array[l]
  if curr_value == Target_sum:
    sum_subarr.append(array[l+1:i+1])
print(sum_subarr)

"""Rotate Array to the Left by k Positions"""

array1 = [10, 20, 20, 30, 40, 50, 50]
k = int(input("By how many positions do we have to rotate left"))
right_array = array1[:k]
left_array = array1[k:]
rotated_array = left_array + right_array
print(rotated_array)

"""Find the Kth Smallest Element"""

l = [11,48,33,274,623,84,524,22,121,54,47,87,33,64,52,25,9,54,11,22,33]
k = int(input("which kth smallest number you want to find of the list"))
l.sort()
kth_elem = l[k-1]
print(l)
print(kth_elem)

"""Find All Subarrays

went through a problem so in this when making a nested loop the j part should not have range from 0 to len(l) because then it will give out meaningless empty list as j can be less than i. if start of slicing is lower than end python will give out an empty list.
Fix: will take range from i to len(l)
"""

l = [16, 17, 4, 3, 5, 2]
all_subarrays = []
for i in range(len(l)):
  for j in range(i,len(l)):
    sub = l[i:j+1]
    all_subarrays.append(sub)
print(all_subarrays)

"""Maximum Sum Subarray (Kadane's Algorithm) (not done yet)"""

nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]

current_sum = nums[0]
max_so_far = nums[0]

for i in range(1, len(nums)):
    if nums[i] > (current_sum + nums[i]):
        current_sum = nums[i]
    else:
        current_sum = current_sum + nums[i]

    if current_sum > max_so_far:
        max_so_far = current_sum

print(f"Maximum Subarray Sum: {max_so_far}")

"""Rearrange Array Alternately: Rearrange an array such that elements alternate between the largest and smallest."""

arr = [16, 17, 4, 3, 5, 2]
l = []
n = len(arr)
left_pointer = 0
right_pointer = -1
for i in range(n):
    min_idx = i
    for j in range(i + 1, n):
        if arr[j] < arr[min_idx]:
            min_idx = j
    arr[i], arr[min_idx] = arr[min_idx], arr[i]
for i in range(len(arr)):
  if i % 2 ==0:
    l.append(arr[left_pointer])
    left_pointer += 1
  else:
    l.append(arr[right_pointer])
    right_pointer -= 1
print(l)

"""Find Majority Element: Find the element that appears more than n/2 times."""

l = [3, 2, 3, 4, 3, 3, 5]
count_dict = {}
for i in l:
  if i in count_dict:
    count_dict[i] += 1
  else:
    count_dict[i] = 1
m_elem = max(count_dict, key = count_dict.get)
if count_dict[m_elem] > len(l)/2:
  print(f"the majority element will be {m_elem} appearing {count_dict[m_elem]} times in the list")
else:
  print("there is no majority element in the list ")

"""Find Peak Element: A peak element is greater than its neighbors. Find one such element."""

l = [7, 8, 9, 4, 12]
peak_elem = []
for i in range(len(l)):
  left_side =  i == 0 or l[i] > l[i-1]
  right_side = i == len(l) - 1 or l[i] > l[i+1]
  if left_side and right_side:
    peak_elem.append(l[i])
print(f"the peak element is {peak_elem[0]}")

"""Find the First Missing Positive: Find the smallest positive integer missing in the array."""

l = [3, 4, -1, 1]
positive_l = []
for i in l:
  if i >= 0:
    positive_l.append(i)
for i in range(len(positive_l)):
  min_index = i
  for j in range(i+1,len(positive_l)):
    if positive_l[j] < positive_l[min_index]:
      min_index = j
  positive_l[i], positive_l[min_index] = positive_l[min_index],positive_l[i]

target = 1
for num in positive_l:
  if num == target:
    target += 1
  else:
    print{f"we found the smallest positive integer {target}"}

"""Sort an Array of 0s, 1s, and 2s: Sort an array consisting of only 0s, 1s, and 2s."""

l = [2, 0, 2, 1, 1, 0]
l_index = 0
m_index = 0
h_index = len(l) -1
while m_index <= h_index:
  if l[m_index] == 0:
    l[m_index] , l[l_index] = l[l_index] , l[m_index]
    l_index += 1
    m_index += 1
  elif l[m_index] == 1:
    m_index += 1
  elif l[m_index]  == 2:
    l[m_index] , l[h_index] = l[h_index] , l[m_index]
    h_index -= 1
print (l)

"""Find the Longest Consecutive Sequence: Find the length of the longest consecutive sequence of integers."""

nums = [100, 4, 200, 1, 3, 2]
num_set = set(nums)
longest_streak = 0

for num in num_set:
    if (num - 1) not in num_set:
        current_num = num
        current_streak = 1
        while (current_num + 1) in num_set:
            current_num += 1
            current_streak += 1
        longest_streak = max(longest_streak, current_streak)
print(f"Longest streak length: {longest_streak}")

"""Product of Array Except Self
Given an array, return a new array where each element is the product of all elements except itself.
Do not use division.
"""

nums = [1, 2, 3, 4]
n = len(nums)
res = [1] * n

prefix = 1
for i in range(n):
    res[i] = prefix
    prefix *= nums[i]

suffix = 1
for i in range(n - 1, -1, -1):
    res[i] *= suffix
    suffix *= nums[i]
print(res)

"""Find Equilibrium Index: Find an index such that sum of elements on left = sum on right."""

arr = [-7, 1, 5, 2, -4, 3, 0]
total_sum = sum(arr)
left_sum = 0
equilibrium_index = -1

for i in range(len(arr)):
    total_sum -= arr[i]

    if left_sum == total_sum:
        equilibrium_index = i
        break
    left_sum += arr[i]

print(f"Equilibrium Index yee raha {equilibrium_index}")

"""Find Maximum Product Pair: Find two elements whose product is maximum.

was going to look for every pair but that will take time, fo I will sort and then take the last two elems for product.
Came to a problem casue - * - will give out positive.
I will take two pairs now first two elems and last two elems and compare their products to see who's is bigger
"""

arr = [-10, -3, 5, 6, -20]
arr.sort()
option1 = arr[0] * arr[1]
option2 = arr[-1] * arr[-2]
max_prod = max(option1, option2)
print(f"Maximum Product Pair: {max_prod}")

"""Find Maximum Difference (j > i)
This code is the 4th try as I was taking the min and subtracting from the max.
i.e I did'nt get the question right, my friend told me so
"""

arr = [2, 3, 10, 6, 4, 8, 1]
min_so_far = arr[0]
max_diff = 0

for x in arr:
    if x - min_so_far > max_diff:
        max_diff = x - min_so_far

    if x < min_so_far:
        min_so_far = x

print(f"Maximum Difference: {max_diff}")